name: Test
on:
  push:
    branches:
    - staging
jobs:
  run-action:
    name: Run the action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: npm run test
    - run: npm run build
    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        targetBranch: master
